### ISSUE TITLE
using .pipe 

### ISSUE THREAD

**Issue by sethkane** [felixzapata/gulp-axe-webdriver#1]
I noticed that in this new plugin that none of the examples use .pipe for the Gulp process like gulp-axe-core was using.  Is it possible to do something like this with this plugin, I can't seem to get it to work.

import gulp from 'gulp';
import axe from 'gulp-axe-webdriver';

gulp.task('axe', function(done) {
  var options = {
            browser: 'phantomjs'
    };
    return gulp.src('./dist/index.html')
            .pipe( axe(options, done) );
});

Thoughts?

**Comment by felixzapata** [comment]
hi, the main difference with the previous plugin is the using of the pipe. With the first, you can only check local files passing to the pipe (like in your example).

But, with the pipe system you can't check remote urls, so for this plugin, I 've "sacrificed" (against what a gulp plugin should do) the pipe system to allow check local and remote files.

For your example, you should use `urls` attribute:

``` javascript
import gulp from 'gulp';
import axe from 'gulp-axe-webdriver';

gulp.task('axe', function(done) {
var options = {
browser: 'phantomjs'
urls: ['./dist/index.html']
};
return axe(options, done);
});
```

Anyway, maybe I can to mix both solutions to allow them both systems: the "natural" way and the specific way to test remote urls. But I think that if I do this, you will not be able to mix (in case you need it) local files and remote urls at the same time like in my example of 'With Glob patterns'.
