### ISSUE TITLE
Upgrade Chromedriver to last version

### ISSUE THREAD

**Issue by ffoodd** [felixzapata/gulp-axe-webdriver#11]
It's currently not working with last versions of Chrome…
Or is there a way to use my own chromedriver?

**Comment by felixzapata** [comment]
Hi, maybe it is not working with the last version. I will check it as soon as possible.

**Comment by felixzapata** [comment]
@ffoodd meanwhile I fix some of tests that I think it is not related with the update of the driver, can you try (until I release a new version) to modify in the `package.json` file to `"chromedriver": "2.38.0",` to see if it is valid for you?

**Comment by ffoodd** [comment]
Hmmm after manually upgrading chromedriver, I still have an error but unrelated to chromedriver:
`TypeError: axe.a11yCheck is not a function`.

Chrome and chromedriver are:
``` 
(Session info: chrome=65.0.3325.181)
(Driver info: chromedriver=2.38.552522)
```
which seems good.

Might it be only be related to `a11ycheck()` function?

**Comment by felixzapata** [comment]
@ffoodd when do you get this error about the `a11ycheck` function?

**Comment by felixzapata** [comment]
@ffoodd I've fixed the problems with the test and I've published the version 1.4.1 with the new chromedriver version. 

By the way, can you paste the example of your gulp configuration task to look for any problem with the `a11ycheck` function?

**Comment by felixzapata** [comment]
I've also published a major version with updates of the core libraries of aXe and removing the Phantomjs (it was neccesary in order to update the libraries. I had it in my TODO list. I will try to add as soon as possible support for Headless Chrome).

**Comment by ffoodd** [comment]
Here is my current Gulp task:
```
gulp.task('axe', function(done) {
  var options = {
    saveOutputIn: 'axe.json',
    folderOutputReport: 'reports',
    urls: [
      test.home,
      test.elms,
      test.grps,
      test.cmps,
      test.gphs
    ]
  };
  return axe(options, done);
});
```
URLs are local ones, eg: `./docs/index.html`.

I'll update this package to check if I'm able to run this again. Thanks for your prompt response!

**Comment by ffoodd** [comment]
It's working `\o/` 
Thanks a lot!
