### ISSUE TITLE
ScriptTimeoutError

### ISSUE THREAD

**Issue by okeul** [felixzapata/gulp-axe-webdriver#14]
Hi,

It works well on a folder that contains a few HTML files but on a folder that that contains a lot of HTML files it doesn't work anymore.

```
ScriptTimeoutError: asynchronous script timeout: result was not received in 0.5 seconds
```

![error](https://user-images.githubusercontent.com/6248074/40735424-7123d232-643b-11e8-9b57-c8a75479aafd.jpg)

Maybe i'm wrong but I think this error comes from this line :
https://github.com/felixzapata/gulp-axe-webdriver/blob/2613bdb465e60f8a2c659995a66c358b591f3c8a/test/test.js#L23

Do you think it's possible to increase this value of 30000 ms ? or bypass it ? 

Thanks you,

**Comment by felixzapata** [comment]
hi @okeul , that timeout it is only for the tests. How many html files are in your folder? I think I' ve seen this error in the past when I've tried to test a remote url with many ads.

Or maybe some of your html files have async scripts to external resources.

**Comment by okeul** [comment]
You're right, i was in the wrong file (test/test.js). Moreover, the value of 30000 ms doesn't match with the value in the error log (0.5 s).

I think this error comes from this line : 
https://github.com/felixzapata/gulp-axe-webdriver/blob/2613bdb465e60f8a2c659995a66c358b591f3c8a/index.js#L32

I did a double check and I feel that it is the network latency that is involved and not the number of HTML file. 

So same question, do you think it's possible to increase this value of 500 ms ? or bypass it ?

**Comment by felixzapata** [comment]
I can increase the value but it should no be bypassed it. Can you run your task with a different value of 500 ms to check what will be the correct value for you?

By the way, inside your HTML files are there scripts to external resources? ads? or whatever other non local resource?

**Comment by okeul** [comment]
According to this issue https://github.com/angular/protractor/issues/117#issuecomment-25335765 it works well with 60000 ms.

Yes i did a test with just one HTML files and it fails because of third-party resources that are time consuming.

**Comment by felixzapata** [comment]
in your case, does it work with 60000 ms? And just for curiosity and if it is possible to know it, what third-party resources do you have in your HTML?

**Comment by okeul** [comment]
Yes in my case it works with 60000 ms. 

I can't say the name sorry but I'm sure you know it. It's a famous third-party in ads ;-)

**Comment by felixzapata** [comment]
ok, I will increase the value in the task.

**Comment by okeul** [comment]
I did a quick PR https://github.com/felixzapata/gulp-axe-webdriver/pull/15

**Comment by felixzapata** [comment]
ok, I will take a look ASAP.

**Comment by felixzapata** [comment]
@okeul I've just published version 2.1.1. Thanks for the pull request.

**Comment by ryuran** [comment]
@felixzapata @okeul, I think this value should be moved to settings

**Comment by felixzapata** [comment]
hi @ryuran, can you make a pull request with that change?

**Comment by okeul** [comment]
PR : https://github.com/felixzapata/gulp-axe-webdriver/pull/19
