### ISSUE TITLE
Currently does not accept "context" attributes

### ISSUE THREAD

**Issue by sethkane** [felixzapata/gulp-axe-webdriver#2]
I appears that your plugin does not accept the context attributes that axe-core utilizes.
[https://github.com/dequelabs/axe-core/blob/master/doc/API.md#parameters-2](https://github.com/dequelabs/axe-core/blob/master/doc/API.md#parameters-2)

It would be awesome if this was included!

**Comment by felixzapata** [comment]
@sethkane there is a new release: 1.1.0

**Comment by sethkane** [comment]
@felixzapata  BRILLIANT.  It works great! Thank you so much!

**Comment by felixzapata** [comment]
@sethkane you're welcome
