### ISSUE TITLE
Scripting actions

### ISSUE THREAD

**Issue by jasonday** [felixzapata/gulp-axe-webdriver#27]
Do you have an example of how to include actions/scripting (such as `click button`) when using gulp-axe-webdriver?

**Comment by felixzapata** [comment]
what do you mean?

**Comment by jasonday** [comment]
I was hoping for an example using selenium webdriver actions:
https://www.softwaretestingmaterial.com/keyboard-mouse-events-using-selenium-actions-class/

For example, click to open a modal then run axe.

**Comment by felixzapata** [comment]
hi, sorry I haven't an example like that. 

Maybe I am wrong but I think it is out of the scope of this plugin.

**Comment by jasonday** [comment]
Ah. I'll take a deeper look, as selenium webdriver is one of the dependencies.

**Comment by delrueba** [comment]
@jasonday did you find a solution for this?
I'd like to set a cookie before the checks are run, but don't see how to access the WebDriver.
