### ISSUE TITLE
Currently does not accept "axe:options" parameter

### ISSUE THREAD

**Issue by sethkane** [felixzapata/gulp-axe-webdriver#3]
As far as I can tell your wrapper does not allow for the axe specific options to be passed in as a parameter.

It would be great if you can leverage more of the API
https://github.com/dequelabs/axe-core/blob/master/doc/API.md#options-parameter

**Comment by felixzapata** [comment]
I will check it.

**Comment by felixzapata** [comment]
@sethkane there is a new release: 1.2.0
