### ISSUE TITLE
Update to axe-core 2.0.7

### ISSUE THREAD

**Issue by sethkane** [felixzapata/gulp-axe-webdriver#5]
Can you update your plugin to use 2.0.7. I am getting a few false positive on the results and I think it is related to their updates.

Here is the weird results I am getting.

 1. ["body > .style-guide > header > .subtitle"]
       Fix any of the following:
        • Element has insufficient color contrast of 3.00 (foreground color: #ffffff, background color: #00a890, font size: 22.5pt, font weight: bold)

   2. ["body > .style-guide > header > h1"]
       Fix any of the following:
        • Element has insufficient color contrast of 3.00 (foreground color: #ffffff, background color: #00a890, font size: 28.5pt, font weight: bold)

This might be an issue with AXE itself.

**Comment by felixzapata** [comment]
hi @sethkane have you test your results with the 2.0.7 version? Anyway it is weird because in the Github page says that the last version is 2.0.5 but in the npm webpage says is 2.0.7. I´ve just asked to Deque Labs about this.

**Comment by sethkane** [comment]
I updated my local version of your code to 2.0.7 and it didn't help so I created some tickets on AXE-CORE page too.

**Comment by felixzapata** [comment]
hi @sethkane, for your information I´ve published the 1.3.0 version that includes (among other things) `axe-core` updated to 2.0.7.

**Comment by sethkane** [comment]
I am getting this error when I am trying to do an update

`
Done. Phantomjs binary available at /Users/sethk/Documents/wwwdev/a11y-testing/node_modules/gulp-axe-webdriver/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/sethk/.nvm/versions/node/v4.3.2/bin/node" "/Users/sethk/.nvm/versions/node/v4.3.2/bin/npm" "install"
npm ERR! node v4.3.2
npm ERR! npm  v2.14.12
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package axe-core@2.1.7 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer axe-webdriverjs@0.4.0 wants axe-core@~2.0.5

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/sethk/Documents/wwwdev/a11y-testing/npm-debug.log
`


Thoughts?

**Comment by felixzapata** [comment]
@sethkane The new version of axe-core has been released this week. I think it is because [the axe-webdriverjs has a dependency](https://github.com/dequelabs/axe-webdriverjs/blob/master/package.json) with the aXe core version 2.0.5.

I´ve made a test removing my `node_modules` folder and installing again the modules. I only see a warning:

`npm WARN axe-webdriverjs@0.4.0 requires a peer of axe-core@~2.0.5 but none was installed.`

Wich version of node and npm do you have? My versions are 6.3.1 and 3.10.3.

Anyway, I will report them an issue.

**Comment by sethkane** [comment]
I am using a much older version of node and npm which I can't change on my work machine but will try it from my home machine tonight.  Thanks for the update I will double check it later.

**Comment by felixzapata** [comment]
@sethkane It is related with the use of ~ symbol instead of the ^. [Due to the `~2.0.5`](https://semver.npmjs.com/), you can´t get the version 2.1.7. 

[I will create them a pull request](https://github.com/dequelabs/axe-webdriverjs/pull/20).

**Comment by sethkane** [comment]
How can I fix this in the meantime?

**Comment by felixzapata** [comment]
The pull request I did was merged yesterday. I've asked them if they are going to release a new version with the change.

You told me that you use an old version of npm, is it correct?

**Comment by sethkane** [comment]
Yeah I am on npm 2.14.12


--------------------------------------------------------------
Seth M. Kane
Cell: 773.531.6010

**Comment by felixzapata** [comment]
do you have the old `axe-webdriverjs` folder inside your `node_modules` folder? It is to modify the `package.json` file and replace `"axe-core": "~2.0.5"` with "axe-core": "^2.0.5"

**Comment by sethkane** [comment]
That worked thanks!


--------------------------------------------------------------
Seth M. Kane
Cell: 773.531.6010

**Comment by felixzapata** [comment]
hi @sethkane , the new version 1.4.0 includes an update with the new `axe-core`.

**Comment by sethkane** [comment]
Great thanks, but now I get this error.

[21:58:45] Requiring external module babel-register

/Users/sethk/Documents/wwwdev/a11y-testing/node_modules/gulp-axe-webdriver/node_modules/selenium-webdriver/index.js:115

  static createSession(...args) {}

                       ^^^

SyntaxError: Unexpected token ...

    at exports.runInThisContext (vm.js:53:16)

    at Module._compile (module.js:373:25)

    at Module._extensions..js (module.js:416:10)

    at Object.require.extensions.(anonymous function) [as .js]
(/Users/sethk/Documents/wwwdev/a11y-testing/node_modules/babel-register/lib/node.js:152:7)

    at Module.load (module.js:343:32)

    at Function.Module._load (module.js:300:12)

    at Module.require (module.js:353:17)

    at require (internal/module.js:12:17)

    at Object.<anonymous>
(/Users/sethk/Documents/wwwdev/a11y-testing/node_modules/gulp-axe-webdriver/index.js:6:17)

    at Module._compile (module.js:409:26)

**Comment by felixzapata** [comment]
hi @sethkane I can't reproduce your issue. I've executed the tests and some examples I have. I've removed the `node_modules` folder too, and installed it again a couple of times but without errors.

Which version of node do you have? Can you remove the `node_modules` folder?

**Comment by sethkane** [comment]
updated node and it works great.
